---
title: "Tikz Annotate"
output:
  html_document: 
    code_folding: hide
  pdf_document: default
---

Annotating text output on the fly....

**Step 1.** First, run whatever command that generates what you want to annotate and use `capture.output` and `textplot` to save it to a `.png` file.

```{r message=FALSE}
model <- lm(mpg ~ wt, mtcars)

captured_text <- capture.output(summary(model))

png("model_summary.png", width=2, height=1, units="in", res=300, pointsize=2)
gplots::textplot(captured_text, mar=c(0,0,0,0))
invisible(dev.off())
```

**Step 2.** Next, use tikz to annotate the `.png` you just created.

**Step 3.** You're done. There's no step 3.

Code is available here: <a href="http://github.com/altaf-ali/tikz_annotate" target="_blank">http://github.com/altaf-ali/tikz_annotate</a>

```{r tikz-ex1, engine = "tikz", fig.width=8}
\input{../PUBLG100/tikz/tikzlibraryannotate.code}
\definecolor{darkgreen}{RGB}{0,128,0}
		  
\begin{annotated_figure}{model_summary.png}
	\annotate{1}{blue, fill=blue, opacity=0.05}{0.100, 0.62}{11cm}{1.1cm}{west}{blue}{east}
	\annotate{2}{red,  fill=red,  opacity=0.05}{0.256, 0.35}{2.3cm}{2cm}{north}{red}{south}
	\annotate{3}{red,  fill=red,  opacity=0.05}{0.371, 0.35}{2.8cm}{2cm}{north}{red}{south}
	\annotate{4}{red,  fill=red,  opacity=0.05}{0.509, 0.35}{2.0cm}{2cm}{north}{red}{south}
	\annotate{5}{red,  fill=red,  opacity=0.05}{0.610, 0.35}{3.3cm}{2cm}{north}{red}{south}
	\annotate{6}{darkgreen, fill=darkgreen, opacity=0.05}{0.100, 0.125}{17cm}{0.5cm}{west}{darkgreen}{east}
\end{annotated_figure}
```


```{r}
knitr::kable(tibble::tribble(
  ~Statistic,   ~Description,
  "Residuals",  "difference between observed and predicted values",
  "Estimate",   "...",
  "Std. error", "...",
  "t-value",    "...",
  "p-value",    "...",
  "R-squared",  "..."
), row.names = TRUE)
```
